"""Smoke tests for Agent Factory (slice 04 — tmp dirs, auto_commit=False)."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from agents.factory.agent_factory import AgentFactory, get_agent_factory, reset_agent_factory
from agents.registry import get_agent_registry, reset_agent_registry
from models.state import MyceliumGraphState, EntityQuery


def _setup_factory_env(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> tuple[Path, Path, Path]:
    reg_path = tmp_path / "reg.json"
    specialists_dir = tmp_path / "specialists"
    data_dir = tmp_path / "agent_data"
    monkeypatch.setenv("MYCELIUM_AGENT_REGISTRY_PATH", str(reg_path))
    monkeypatch.setenv("MYCELIUM_SPECIALISTS_DIR", str(specialists_dir))
    monkeypatch.setenv("MYCELIUM_AGENT_DATA_DIR", str(data_dir))
    monkeypatch.delenv("OPENAI_API_KEY", raising=False)
    monkeypatch.delenv("TAVILY_API_KEY", raising=False)
    reset_agent_registry()
    reset_agent_factory()
    return reg_path, specialists_dir, data_dir


@pytest.mark.smoke
def test_create_specialist_writes_files_and_registers(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    _reg_path, specialists_dir, data_dir = _setup_factory_env(tmp_path, monkeypatch)
    factory = get_agent_factory()

    info = factory.create_specialist(
        "contact",
        "contact_specialist",
        "Direct contact info",
        examples=["email", "phone"],
        auto_commit=False,
    )

    assert info["created"] is True
    assert info["committed"] is False
    assert info["fn_loaded"] is True

    py_path = specialists_dir / "contact_specialist.py"
    assert py_path.exists()
    text = py_path.read_text(encoding="utf-8")
    assert "AUTO-GENERATED by Agent Factory" in text
    assert "contact" in text
    assert "SpecialistStorage" in text
    assert "def contact_specialist(" in text
    assert "core_identity" not in text
    assert "_resolve_id" in text
    assert "entity_id" in text
    assert "_identity_from_context" in text
    assert "bind" in text
    assert "current_id" in text
    assert "specialist_contrib" in text
    assert "assemble_response builds the public message" in text
    assert "not currently available but may be in the future" not in text

    registry = get_agent_registry()
    assert registry.has_agent("contact_specialist")
    fn = registry.get_agent_fn("contact_specialist")
    assert callable(fn)

    strategy_path = data_dir / "contact" / "storage_strategy.json"
    storage_path = data_dir / "contact" / "storage.json"
    assert strategy_path.exists()
    assert storage_path.exists()

    state = MyceliumGraphState(query=EntityQuery(entity_key="__no_such_person__"))
    result = fn(state)
    assert "response" in result
    assert result["response"].results == []
    assert result.get("specialist_contrib", {}).get("status") == "not_found"

    test_id = "test-person-uuid-1540"
    state_pending = MyceliumGraphState(
        query=EntityQuery(entity_key="Test User", requested_attributes=["email"]),
        current_id=test_id,
        context={
            "entity_id": test_id,
            "bind": {"name": "Test User", "employer": "Co"},
            "specialists": {},
        },
        target_fields=["email"],
    )
    result_pending = fn(state_pending)
    assert result_pending["specialist_contrib"]["status"] == "pending"
    assert result_pending["specialist_contrib"]["id"] == test_id
    assert "Classified email as contact" in result_pending["response"].message
    assert "not currently available but may be in the future" not in result_pending["response"].message
    stored = json.loads(storage_path.read_text(encoding="utf-8"))
    assert stored["records"][test_id]["email"]["status"] == "pending"


@pytest.mark.smoke
def test_create_specialist_second_call_is_noop(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    _setup_factory_env(tmp_path, monkeypatch)
    factory = get_agent_factory()

    first = factory.create_specialist(
        "social",
        "social_specialist",
        "Social profiles",
        auto_commit=False,
    )
    second = factory.create_specialist(
        "social",
        "social_specialist",
        "Social profiles",
        auto_commit=False,
    )

    assert first["created"] is True
    assert second == {"created": False, "reason": "already registered"}


@pytest.mark.smoke
def test_create_specialist_llm_refine_stub(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    _, specialists_dir, _ = _setup_factory_env(tmp_path, monkeypatch)

    def _fake_refine(self: AgentFactory, code: str, agent_name: str) -> str:
        _ = self, agent_name
        return code.replace(
            "DO NOT EDIT THIS FILE BY HAND",
            "REFINED_BY_TEST_MARKER\nDO NOT EDIT THIS FILE BY HAND",
        )

    monkeypatch.setattr(AgentFactory, "_refine_with_llm", _fake_refine)
    factory = get_agent_factory()

    factory.create_specialist(
        "demo",
        "demo_specialist",
        "Demo category",
        llm_refine=True,
        auto_commit=False,
    )

    text = (specialists_dir / "demo_specialist.py").read_text(encoding="utf-8")
    assert "REFINED_BY_TEST_MARKER" in text


@pytest.mark.smoke
def test_agent_factory_refine_with_mock_llm(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    _setup_factory_env(tmp_path, monkeypatch)
    factory = get_agent_factory()
    sample = (
        '"""contact_specialist — auto-generated."""\n\n'
        "def contact_specialist(state):\n"
        "    return {}\n"
    )

    class _FakeResponse:
        content = (
            "# REFINED_BY_LLM\n"
            + sample
            + "\n# end\n"
        )

    class _FakeLLM:
        def invoke(self, prompt: str) -> _FakeResponse:
            _ = prompt
            return _FakeResponse()

    monkeypatch.setattr(
        "langchain_openai.ChatOpenAI",
        lambda *args, **kwargs: _FakeLLM(),
    )

    refined = factory._refine_with_llm(sample, "contact_specialist")
    assert "REFINED_BY_LLM" in refined
    assert "def contact_specialist" in refined

    class _BadLLM:
        def invoke(self, prompt: str) -> object:
            _ = prompt
            return type("R", (), {"content": "invalid without def"})()

    monkeypatch.setattr(
        "langchain_openai.ChatOpenAI",
        lambda *args, **kwargs: _BadLLM(),
    )
    assert factory._refine_with_llm(sample, "contact_specialist") == sample
