"""contact_specialist — auto-generated specialist agent for category "contact".

AUTO-GENERATED by Agent Factory on 2026-06-04T15:42:32.658785+00:00.
Category: contact
Description: Direct ways to reach the person (email, phone, physical).
Examples: email, phone, mobile, address, website

DO NOT EDIT THIS FILE BY HAND UNLESS YOU MEAN IT.
- Preferred: edit the template (src/agents/factory/templates/specialist_agent.py.j2) and re-generate via factory.
- Acceptable: edit this file directly (it is committed source). Future readers will see the header.
- Storage strategy + data live beside this file in data/agents/contact/ (see storage_strategy.json).
- Records are keyed by person_id (stable UUID from seed loader). See agents/specialists/base.py.

First-class owner of contact data in the seed + specialist context model.
Receives context, person_id, and owned fields from supervisor/graph (not CoreIdentity).

Three scenarios (seed-data-context redesign):
  1. Specialist already has the requested owned data → return it (context optional).
  2. No data yet → mark pending, start background research stub, return "not currently available
     but may be in the future" (pending prevents duplicate threads).
  3. Previously researched and marked N/A → return N/A for that field.

Fields passed to this specialist: only attributes it owns (target_fields / classifications).
"""

from __future__ import annotations

import threading
from datetime import datetime, timezone
from typing import Any

from agents.responses import response_found, response_non_core, response_not_found
from agents.specialists.base import SpecialistStorage
from models.state import MyceliumGraphState

# TODO: revisit this later to make sure it's robust — e.g., research thread dying and
# leaving "pending" forever.

_storage: SpecialistStorage | None = None


def get_specialist_storage() -> SpecialistStorage:
    """Lazy per-module storage (respects MYCELIUM_AGENT_DATA_DIR for tests)."""
    global _storage
    if _storage is None:
        _storage = SpecialistStorage(category="contact")
    return _storage


def _coerce(state: MyceliumGraphState | dict[str, Any]) -> MyceliumGraphState:
    if isinstance(state, MyceliumGraphState):
        return state
    return MyceliumGraphState.model_validate(state)


def _resolve_invocation_ids(state: MyceliumGraphState) -> tuple[str | None, str | None]:
    return state.invocation_thread_id, state.invocation_trace_id


def _resolve_person_id(state: MyceliumGraphState) -> str | None:
    if state.current_person_id:
        return state.current_person_id
    ctx = state.context if isinstance(state.context, dict) else {}
    seed = ctx.get("seed")
    if isinstance(seed, dict):
        return seed.get("person_id")
    if isinstance(seed, list) and len(seed) == 1 and isinstance(seed[0], dict):
        return seed[0].get("person_id")
    if state.matched_persons and len(state.matched_persons) == 1:
        return state.matched_persons[0].get("person_id")
    return None


def _resolve_owned_fields(state: MyceliumGraphState) -> list[str]:
    if state.target_fields:
        return list(state.target_fields)
    owned: list[str] = []
    for cl in state.classifications or []:
        if cl.get("category") == "contact" and cl.get("attribute"):
            owned.append(cl["attribute"])
    if owned:
        return owned
    return [
        a.strip().lower()
        for a in state.query.requested_attributes
        if a.strip()
    ] or ["contact data"]


def _identity_from_context(ctx: dict[str, Any]) -> list[dict[str, Any]]:
    seed = ctx.get("seed")
    if isinstance(seed, dict):
        rows = [seed]
    elif isinstance(seed, list):
        rows = [r for r in seed if isinstance(r, dict)]
    else:
        rows = []
    records: list[dict[str, Any]] = []
    for rec in rows:
        pid = rec.get("person_id", "")
        records.append(
            {
                "id": pid,
                "name": rec.get("name", ""),
                "employer": rec.get("employer"),
                "person_id": pid,
            },
        )
    return records


def _field_has_value(entry: Any) -> bool:
    if entry is None:
        return False
    if isinstance(entry, dict):
        status = entry.get("status")
        if status in ("pending", "na"):
            return False
        return "value" in entry or status == "found"
    return True


def _field_is_pending(entry: Any) -> bool:
    return isinstance(entry, dict) and entry.get("status") == "pending"


def _field_is_na(entry: Any) -> bool:
    return isinstance(entry, dict) and entry.get("status") == "na"


def _field_display_value(entry: Any) -> str:
    if isinstance(entry, dict):
        if entry.get("status") == "na":
            return "N/A"
        return str(entry.get("value", entry.get("status", "")))
    return str(entry)


def _stub_background_research(
    person_id: str,
    owned_fields: list[str],
    ctx: dict[str, Any],
    storage: SpecialistStorage,
) -> None:
    """Stub research thread (LLM+tools + persist results deferred to a later phase)."""
    _ = ctx, owned_fields
    # Placeholder: real implementation will use context (seed + other specialists) here.


def _start_research_if_needed(
    person_id: str,
    field: str,
    owned_fields: list[str],
    ctx: dict[str, Any],
    storage: SpecialistStorage,
) -> None:
    data = storage.load()
    records = data.setdefault("records", {})
    rec = records.setdefault(person_id, {})
    if _field_is_pending(rec.get(field)) or _field_has_value(rec.get(field)):
        return
    rec[field] = {
        "status": "pending",
        "started_at": datetime.now(timezone.utc).isoformat(),
    }
    storage.save(data)
    thread = threading.Thread(
        target=_stub_background_research,
        args=(person_id, owned_fields, ctx, storage),
        daemon=True,
        name=f"contact_specialist-research-{person_id[:8]}",
    )
    thread.start()


def _evaluate_owned_fields(
    person_id: str,
    owned: list[str],
    ctx: dict[str, Any],
    storage: SpecialistStorage,
) -> tuple[dict[str, Any], str, list[str]]:
    """
    Apply the 3 scenarios per owned field.

    Returns (values map, overall status, attrs still pending/unavailable).
    """
    data = storage.load()
    rec = data.get("records", {}).get(person_id, {})
    values: dict[str, Any] = {}
    pending_attrs: list[str] = []
    na_attrs: list[str] = []
    found_attrs: list[str] = []

    for field in owned:
        entry = rec.get(field)
        if _field_has_value(entry):
            values[field] = _field_display_value(entry)
            found_attrs.append(field)
        elif _field_is_na(entry):
            values[field] = "N/A"
            na_attrs.append(field)
        elif _field_is_pending(entry):
            values[field] = "pending"
            pending_attrs.append(field)
        else:
            _start_research_if_needed(person_id, field, owned, ctx, storage)
            values[field] = "pending"
            pending_attrs.append(field)

    if pending_attrs:
        overall = "pending"
    elif found_attrs and not na_attrs:
        overall = "found"
    elif na_attrs and not found_attrs and not pending_attrs:
        overall = "na"
    else:
        overall = "mixed"

    return values, overall, pending_attrs


def contact_specialist(state: MyceliumGraphState | dict[str, Any]) -> dict[str, Any]:
    """
    Specialist for "contact": context + person_id + owned fields only.

    Synchronous graph node; returns response + specialist_contrib for downstream assembly.
    """
    current = _coerce(state)
    ctx = current.context if isinstance(current.context, dict) else {}
    person_id = _resolve_person_id(current)
    owned = _resolve_owned_fields(current)
    my_store = get_specialist_storage()
    thread_id, trace_id = _resolve_invocation_ids(current)
    id_kwargs = {"thread_id": thread_id, "trace_id": trace_id}
    clf_kwargs = (
        {"classifications": current.classifications}
        if current.classifications
        else {}
    )
    identity_records = _identity_from_context(ctx)

    if not person_id:
        resp = response_not_found(current.query, specialist="contact_specialist", **id_kwargs, **clf_kwargs)
        contrib = {"person_id": None, "fields": owned, "values": {}, "status": "not_found"}
        return {
            "response": resp,
            "route": None,
            "audit_log": [
                f"contact_specialist: no person_id in state for {current.query.person_key!r}.",
            ],
            "specialist_contrib": contrib,
            "matched_persons": current.matched_persons or [],
            "classifications": current.classifications or [],
            **({"invocation_thread_id": thread_id} if thread_id else {}),
            **({"invocation_trace_id": trace_id} if trace_id else {}),
        }

    values, overall_status, pending_attrs = _evaluate_owned_fields(
        person_id,
        owned,
        ctx,
        my_store,
    )

    contrib: dict[str, Any] = {
        "person_id": person_id,
        "category": "contact",
        "fields": owned,
        "values": values,
        "status": overall_status,
    }

    if overall_status == "found":
        message_extra = ", ".join(f"{k}: {v}" for k, v in values.items())
        resp = response_found(
            current.query,
            base_records=identity_records or None,
            specialist="contact_specialist",
            **id_kwargs,
            **clf_kwargs,
        )
        if message_extra:
            resp = resp.model_copy(
                update={"message": f"{resp.message} {message_extra}."},
            )
        outcome = "found"
    elif overall_status == "na":
        na_list = ", ".join(owned)
        resp = response_non_core(
            current.query,
            base_records=identity_records or None,
            attributes=[f"{a} (N/A)" for a in owned],
            specialist="contact_specialist",
            **id_kwargs,
            **clf_kwargs,
        )
        resp = resp.model_copy(
            update={
                "message": (
                    f"Found record for {identity_records[0]['name'] if identity_records else current.query.person_key}. "
                    f"{na_list} marked N/A (via contact_specialist)."
                ),
            },
        )
        outcome = "na"
    else:
        attr_list = ", ".join(pending_attrs or owned)
        resp = response_non_core(
            current.query,
            base_records=identity_records or None,
            attributes=pending_attrs or owned,
            specialist="contact_specialist",
            **id_kwargs,
            **clf_kwargs,
        )
        resp = resp.model_copy(
            update={
                "message": (
                    f"Found record for {identity_records[0]['name'] if identity_records else current.query.person_key}. "
                    f"{attr_list} not currently available but may be in the future "
                    f"(via contact_specialist)."
                ),
            },
        )
        outcome = "pending"

    store_snapshot = my_store.load()
    record_count = len(store_snapshot.get("records", {}))
    logs = [
        f"contact_specialist: {outcome} for person_id={person_id!r} (category=contact).",
        f"contact_specialist: specialist store has {record_count} record(s).",
    ]

    payload: dict[str, Any] = {
        "response": resp,
        "route": None,
        "audit_log": logs,
        "specialist_contrib": contrib,
        "matched_persons": current.matched_persons or [],
        "classifications": current.classifications or [],
        "context": ctx,
        "current_person_id": person_id,
        "target_fields": owned,
    }
    if identity_records and len(identity_records) == 1:
        from models.state import Person

        ir = identity_records[0]
        payload["person"] = Person(
            id=ir.get("person_id", "") or ir.get("id", ""),
            person_id=ir.get("person_id", "") or ir.get("id", ""),
            name=ir.get("name", ""),
            employer=ir.get("employer"),
        )
    if current.invocation_thread_id is not None:
        payload["invocation_thread_id"] = current.invocation_thread_id
    if current.invocation_trace_id is not None:
        payload["invocation_trace_id"] = current.invocation_trace_id
    return payload