"""demographic_specialist — auto-generated specialist agent for category "demographic".

AUTO-GENERATED by Agent Factory on 2026-06-04T19:21:48.362611+00:00.
Category: demographic
Description: Basic personal characteristics and background.
Examples: age, birthday, gender, nationality, location

DO NOT EDIT THIS FILE BY HAND UNLESS YOU MEAN IT.
- Preferred: edit the template (src/agents/factory/templates/specialist_agent.py.j2) and re-generate via factory.
- Acceptable: edit this file directly (it is committed source). Future readers will see the header.
- Storage strategy + data live beside this file in data/agents/demographic/ (see storage_strategy.json).
- Records are keyed by id (stable UUID from seed loader). See agents/specialists/base.py.

First-class owner of demographic data in the seed + specialist context model.
Receives context, id, and owned fields from supervisor/graph (not CoreIdentity).

Three scenarios (seed-data-context redesign):
  1. Specialist already has the requested owned data → return it (context optional).
  2. No data yet → run synchronous field research when API keys are configured; otherwise
     mark pending and return "not currently available but may be in the future".
  3. Previously researched and marked N/A → return N/A for that field.

Phase 1: research runs inline in this node (async dispatch deferred).

Fields passed to this specialist: only attributes it owns (target_fields / classifications).
"""

from __future__ import annotations

import os
from datetime import datetime, timezone
from typing import Any

from agents.responses import response_found, response_non_core, response_not_found
from agents.specialists.base import SpecialistStorage
from models.state import MyceliumGraphState

_storage: SpecialistStorage | None = None


def get_specialist_storage() -> SpecialistStorage:
    """Lazy per-module storage (respects MYCELIUM_AGENT_DATA_DIR for tests)."""
    global _storage
    if _storage is None:
        _storage = SpecialistStorage(category="demographic")
    return _storage


def _coerce(state: MyceliumGraphState | dict[str, Any]) -> MyceliumGraphState:
    if isinstance(state, MyceliumGraphState):
        return state
    return MyceliumGraphState.model_validate(state)


def _resolve_invocation_ids(state: MyceliumGraphState) -> tuple[str | None, str | None]:
    return state.invocation_thread_id, state.invocation_trace_id


def _resolve_id(state: MyceliumGraphState) -> str | None:
    if state.current_id:
        return state.current_id
    ctx = state.context if isinstance(state.context, dict) else {}
    seed = ctx.get("seed")
    if isinstance(seed, dict):
        return seed.get("id")
    if isinstance(seed, list) and len(seed) == 1 and isinstance(seed[0], dict):
        return seed[0].get("id")
    if state.matched_persons and len(state.matched_persons) == 1:
        return state.matched_persons[0].get("id")
    return None


def _resolve_owned_fields(state: MyceliumGraphState) -> list[str]:
    if state.target_fields:
        return list(state.target_fields)
    owned: list[str] = []
    for cl in state.classifications or []:
        if cl.get("category") == "demographic" and cl.get("attribute"):
            owned.append(cl["attribute"])
    if owned:
        return owned
    return [
        a.strip().lower()
        for a in state.query.requested_attributes
        if a.strip()
    ] or ["demographic data"]


def _identity_from_context(ctx: dict[str, Any]) -> list[dict[str, Any]]:
    seed = ctx.get("seed")
    if isinstance(seed, dict):
        rows = [seed]
    elif isinstance(seed, list):
        rows = [r for r in seed if isinstance(r, dict)]
    else:
        rows = []
    records: list[dict[str, Any]] = []
    for rec in rows:
        pid = rec.get("id", "")
        records.append(
            {
                "id": pid,
                "name": rec.get("name", ""),
                "employer": rec.get("employer"),
            },
        )
    return records


def _field_has_value(entry: Any) -> bool:
    if entry is None:
        return False
    if isinstance(entry, dict):
        status = entry.get("status")
        if status in ("pending", "na"):
            return False
        return "value" in entry or status == "found"
    return True


def _field_is_pending(entry: Any) -> bool:
    return isinstance(entry, dict) and entry.get("status") == "pending"


def _field_is_na(entry: Any) -> bool:
    return isinstance(entry, dict) and entry.get("status") == "na"


def _field_display_value(entry: Any) -> str:
    if isinstance(entry, dict):
        if entry.get("status") == "na":
            return "N/A"
        return str(entry.get("value", entry.get("status", "")))
    return str(entry)


def _mark_fields_pending(
    pid: str,
    fields: list[str],
    storage: SpecialistStorage,
) -> None:
    if not fields:
        return
    data = storage.load()
    records = data.setdefault("records", {})
    rec = records.setdefault(pid, {})
    now = datetime.now(timezone.utc).isoformat()
    for field in fields:
        if _field_is_pending(rec.get(field)) or _field_has_value(rec.get(field)):
            continue
        if _field_is_na(rec.get(field)):
            continue
        rec[field] = {"status": "pending", "started_at": now}
    storage.save(data)


def _research_retry_pending_enabled() -> bool:
    return os.getenv("MYCELIUM_RESEARCH_RETRY_PENDING", "1").strip().lower() not in (
        "0",
        "false",
        "no",
    )


def _research_retry_pending_sec() -> int:
    raw = (
        os.getenv("MYCELIUM_RESEARCH_RETRY_PENDING_MIN_AGE_SEC", "").strip()
        or os.getenv("MYCELIUM_RESEARCH_RETRY_PENDING_SEC", "0").strip()
    )
    if not raw:
        return 0
    try:
        return max(0, int(raw))
    except ValueError:
        return 0


def _pending_started_at(entry: Any) -> datetime | None:
    if not isinstance(entry, dict):
        return None
    raw = entry.get("started_at")
    if not raw:
        return None
    try:
        return datetime.fromisoformat(str(raw).replace("Z", "+00:00"))
    except ValueError:
        return None


def _pending_is_stale(entry: Any, *, min_age_sec: int) -> bool:
    if min_age_sec <= 0:
        return False
    started = _pending_started_at(entry)
    if started is None:
        return True
    now = datetime.now(timezone.utc)
    if started.tzinfo is None:
        started = started.replace(tzinfo=timezone.utc)
    return (now - started).total_seconds() >= min_age_sec


def _run_field_research(
    pid: str,
    target_fields: list[str],
    ctx: dict[str, Any],
    storage: SpecialistStorage,
) -> Any:
    """Sync Phase 1 research hook (async dispatch can replace this call site later)."""
    from tools.research import ResearchRunResult, is_research_available, run_field_research

    if not is_research_available():
        _mark_fields_pending(pid, target_fields, storage)
        return ResearchRunResult(errors=["research unavailable"])
    return run_field_research(
        category="demographic",
        specialist_name="demographic_specialist",
        person_id=pid,
        target_fields=target_fields,
        context=ctx,
        storage=storage,
    )


def _fields_needing_research(rec: dict[str, Any], owned: list[str]) -> list[str]:
    need: list[str] = []
    retry_on = _research_retry_pending_enabled()
    retry_sec = _research_retry_pending_sec()
    for field in owned:
        entry = rec.get(field)
        if _field_has_value(entry) or _field_is_na(entry):
            continue
        if entry is None:
            need.append(field)
            continue
        if _field_is_pending(entry):
            if not retry_on:
                continue
            if entry.get("last_error"):
                need.append(field)
                continue
            if _pending_is_stale(entry, min_age_sec=retry_sec):
                need.append(field)
            continue
        need.append(field)
    return need


def _evaluate_owned_fields(
    pid: str,
    owned: list[str],
    ctx: dict[str, Any],
    storage: SpecialistStorage,
) -> tuple[dict[str, Any], str, list[str], str | None]:
    """
    Apply the 3 scenarios per owned field.

    Returns (values map, overall status, attrs still pending/unavailable, research audit line).
    """
    research_audit: str | None = None
    data = storage.load()
    rec = data.get("records", {}).get(pid, {})
    need = _fields_needing_research(rec, owned)
    if need:
        _mark_fields_pending(pid, need, storage)
        research_result = _run_field_research(pid, need, ctx, storage)
        updated = list(research_result.fields_updated) if research_result else []
        tool_calls = research_result.tool_calls_count if research_result else 0
        err_count = len(research_result.errors) if research_result else 0
        research_audit = (
            f"demographic_specialist: research id={pid} fields={need!r} "
            f"updated={updated!r} tool_calls={tool_calls} errors={err_count}"
        )
        data = storage.load()
        rec = data.get("records", {}).get(pid, {})

    values: dict[str, Any] = {}
    pending_attrs: list[str] = []
    na_attrs: list[str] = []
    found_attrs: list[str] = []

    for field in owned:
        entry = rec.get(field)
        if _field_has_value(entry):
            values[field] = _field_display_value(entry)
            found_attrs.append(field)
        elif _field_is_na(entry):
            values[field] = "N/A"
            na_attrs.append(field)
        elif _field_is_pending(entry):
            values[field] = "pending"
            pending_attrs.append(field)
        else:
            values[field] = "pending"
            pending_attrs.append(field)

    if pending_attrs:
        overall = "pending"
    elif found_attrs and not na_attrs:
        overall = "found"
    elif na_attrs and not found_attrs and not pending_attrs:
        overall = "na"
    else:
        overall = "mixed"

    return values, overall, pending_attrs, research_audit


def demographic_specialist(state: MyceliumGraphState | dict[str, Any]) -> dict[str, Any]:
    """
    Specialist for "demographic": context + id + owned fields only.

    Synchronous graph node; returns response + specialist_contrib for downstream assembly.
    """
    current = _coerce(state)
    ctx = current.context if isinstance(current.context, dict) else {}
    pid = _resolve_id(current)
    owned = _resolve_owned_fields(current)
    my_store = get_specialist_storage()
    thread_id, trace_id = _resolve_invocation_ids(current)
    id_kwargs = {"thread_id": thread_id, "trace_id": trace_id}
    clf_kwargs = (
        {"classifications": current.classifications}
        if current.classifications
        else {}
    )
    identity_records = _identity_from_context(ctx)

    if not pid:
        resp = response_not_found(current.query, specialist="demographic_specialist", **id_kwargs, **clf_kwargs)
        contrib = {"id": None, "fields": owned, "values": {}, "status": "not_found"}
        return {
            "response": resp,
            "route": None,
            "audit_log": [
                f"demographic_specialist: no id in state for {current.query.person_key!r}.",
            ],
            "specialist_contrib": contrib,
            "matched_persons": current.matched_persons or [],
            "classifications": current.classifications or [],
            **({"invocation_thread_id": thread_id} if thread_id else {}),
            **({"invocation_trace_id": trace_id} if trace_id else {}),
        }

    values, overall_status, pending_attrs, research_audit = _evaluate_owned_fields(
        pid,
        owned,
        ctx,
        my_store,
    )

    contrib: dict[str, Any] = {
        "id": pid,
        "category": "demographic",
        "fields": owned,
        "values": values,
        "status": overall_status,
    }

    if overall_status == "found":
        message_extra = ", ".join(f"{k}: {v}" for k, v in values.items())
        resp = response_found(
            current.query,
            base_records=identity_records or None,
            specialist="demographic_specialist",
            **id_kwargs,
            **clf_kwargs,
        )
        if message_extra:
            resp = resp.model_copy(
                update={"message": f"{resp.message} {message_extra}."},
            )
        outcome = "found"
    elif overall_status == "na":
        na_list = ", ".join(owned)
        resp = response_non_core(
            current.query,
            base_records=identity_records or None,
            attributes=[f"{a} (N/A)" for a in owned],
            specialist="demographic_specialist",
            **id_kwargs,
            **clf_kwargs,
        )
        resp = resp.model_copy(
            update={
                "message": (
                    f"Found record for {identity_records[0]['name'] if identity_records else current.query.person_key}. "
                    f"{na_list} marked N/A (via demographic_specialist)."
                ),
            },
        )
        outcome = "na"
    elif overall_status == "mixed":
        person_name = (
            identity_records[0]["name"]
            if identity_records
            else current.query.person_key
        )
        detail_parts: list[str] = []
        for field in owned:
            val = values.get(field)
            if val and val not in ("N/A", "pending"):
                detail_parts.append(f"Found {field}: {val}")
            elif val == "N/A":
                detail_parts.append(f"{field} marked N/A")
        mixed_detail = "; ".join(detail_parts) or ", ".join(owned)
        resp = response_non_core(
            current.query,
            base_records=identity_records or None,
            attributes=owned,
            specialist="demographic_specialist",
            **id_kwargs,
            **clf_kwargs,
        )
        resp = resp.model_copy(
            update={
                "message": (
                    f"Found record for {person_name}. "
                    f"{mixed_detail} (via demographic_specialist)."
                ),
            },
        )
        outcome = "mixed"
    else:
        attr_list = ", ".join(pending_attrs or owned)
        resp = response_non_core(
            current.query,
            base_records=identity_records or None,
            attributes=pending_attrs or owned,
            specialist="demographic_specialist",
            **id_kwargs,
            **clf_kwargs,
        )
        resp = resp.model_copy(
            update={
                "message": (
                    f"Found record for {identity_records[0]['name'] if identity_records else current.query.person_key}. "
                    f"{attr_list} not currently available but may be in the future "
                    f"(via demographic_specialist)."
                ),
            },
        )
        outcome = "pending"

    store_snapshot = my_store.load()
    record_count = len(store_snapshot.get("records", {}))
    logs = [
        f"demographic_specialist: {outcome} for id={pid!r} (category=demographic).",
        f"demographic_specialist: specialist store has {record_count} record(s).",
    ]
    if research_audit:
        logs.append(research_audit)

    payload: dict[str, Any] = {
        "response": resp,
        "route": None,
        "audit_log": logs,
        "specialist_contrib": contrib,
        "matched_persons": current.matched_persons or [],
        "classifications": current.classifications or [],
        "context": ctx,
        "current_id": pid,
        "target_fields": owned,
    }
    if identity_records and len(identity_records) == 1:
        from models.state import Person

        ir = identity_records[0]
        payload["person"] = Person(
            id=ir.get("id", ""),
            name=ir.get("name", ""),
            employer=ir.get("employer"),
        )
    if current.invocation_thread_id is not None:
        payload["invocation_thread_id"] = current.invocation_thread_id
    if current.invocation_trace_id is not None:
        payload["invocation_trace_id"] = current.invocation_trace_id
    return payload