"""social_specialist — auto-generated specialist agent for category "social".

AUTO-GENERATED by Agent Factory on 2026-06-04T08:37:40.187882+00:00.
Category: social
Description: Social and professional network profiles and handles.
Examples: (none at creation)

DO NOT EDIT THIS FILE BY HAND UNLESS YOU MEAN IT.
- Preferred: edit the template (src/agents/factory/templates/specialist_agent.py.j2) and re-generate via factory.
- Acceptable: edit this file directly (it is committed source). Future readers will see the header.
- Storage strategy + data live beside this file in data/agents/social/ (see storage_strategy.json).
- Future storage evolution hooks are in agents/specialists/base.py (migrate_to etc.). The specialist
  code itself can later contain the intelligence that decides when to evolve its store.

This specialist owns its domain data and storage. It is a first-class peer to core_data.
"""

from __future__ import annotations

from typing import Any

from agents.specialists.base import SpecialistStorage
from agents.core_identity import get_core_identity
from agents.responses import debug_for_query, response_non_core, response_not_found
from models.state import MyceliumGraphState, Person


_storage: SpecialistStorage | None = None


def get_specialist_storage() -> SpecialistStorage:
    """Lazy per-module storage (respects MYCELIUM_AGENT_DATA_DIR for tests)."""
    global _storage
    if _storage is None:
        _storage = SpecialistStorage(category="social")
    return _storage


def _coerce(state: MyceliumGraphState | dict[str, Any]) -> MyceliumGraphState:
    if isinstance(state, MyceliumGraphState):
        return state
    return MyceliumGraphState.model_validate(state)


def _resolve_invocation_ids(state: MyceliumGraphState) -> tuple[str | None, str | None]:
    return state.invocation_thread_id, state.invocation_trace_id


def social_specialist(state: MyceliumGraphState | dict[str, Any]) -> dict[str, Any]:
    """
    Specialist agent for the "social" category.

    Resolves the person via CoreIdentity (so results stay consistent), then
    "looks up" in its own store (initially empty → research narrative).
    Later versions of this specialist can return real data from storage and
    can decide to evolve the storage strategy.

    This is a synchronous function (supports both invoke and ainvoke paths).
    """
    current = _coerce(state)
    identity = get_core_identity()
    matches: list[Person] = identity.find_by_key(current.query.person_key)

    my_store = get_specialist_storage()
    thread_id, trace_id = _resolve_invocation_ids(current)
    id_kwargs = {"thread_id": thread_id, "trace_id": trace_id}
    clf_kwargs = {"classifications": current.classifications} if current.classifications else {}

    my_attrs: list[str] = []
    for c in (current.classifications or []):
        if c.get("category") == "social" and c.get("attribute"):
            my_attrs.append(c["attribute"])
    if not my_attrs:
        my_attrs = [a for a in current.query.requested_attributes]

    if not matches:
        resp = response_not_found(current.query, **id_kwargs, **clf_kwargs)
        outcome = "not_found"
    else:
        resp = response_non_core(
            current.query,
            matches,
            my_attrs or ["social data"],
            specialist="social_specialist",
            **id_kwargs,
            **clf_kwargs,
        )
        outcome = "specialist_researching"

    store_snapshot = my_store.load()
    record_count = len(store_snapshot.get("records", {}))
    logs = [
        f"social_specialist: lookup {outcome} for person_key={current.query.person_key!r} (category=social).",
        f"social_specialist: specialist store has {record_count} record(s).",
    ]

    payload: dict[str, Any] = {
        "response": resp,
        "route": None,
        "audit_log": logs,
        "persons": matches,
        "classifications": current.classifications or [],
    }
    if len(matches) == 1:
        payload["person"] = matches[0]
    if current.invocation_thread_id is not None:
        payload["invocation_thread_id"] = current.invocation_thread_id
    if current.invocation_trace_id is not None:
        payload["invocation_trace_id"] = current.invocation_trace_id
    return payload